"""Add conversation and message models

Revision ID: 62f721b86280
Revises: f5185270fc13
Create Date: 2026-02-08 16:36:06.887895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f721b86280'
down_revision: Union[str, Sequence[str], None] = 'f5185270fc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_column('conversation', 'title')
    op.drop_column('conversation', 'user_id')
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('message', 'tool_calls')
    op.drop_column('message', 'tool_call_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('tool_call_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('tool_calls', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('conversation', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('conversation', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    # ### end Alembic commands ###
