"""add_advanced_task_features

Revision ID: f5185270fc13
Revises: 27077787d24b
Create Date: 2026-02-03 00:30:57.553842

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5185270fc13'
down_revision: Union[str, Sequence[str], None] = '27077787d24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False))
    op.add_column('item', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('item', sa.Column('due_time', sa.Time(), nullable=True))
    op.add_column('item', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('recurrence_pattern', sa.Enum('DAILY', 'WEEKLY', name='recurrencepattern'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'recurrence_pattern')
    op.drop_column('item', 'is_recurring')
    op.drop_column('item', 'due_time')
    op.drop_column('item', 'due_date')
    op.drop_column('item', 'priority')
    # ### end Alembic commands ###
